spring:
  profiles: local
  main:
    banner-mode: "off"
  
  datasource:
    initialize: false 
    url: jdbc:postgresql://localhost:5432/testdb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    tomcat:
      initial-size: 2
      max-active: 5
      
logging:
  level:
    org.springframework.web: ERROR
    com.morrisons: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  security:
    enabled: false

errorTopic: testerrortopic

cloud: 
  aws:
    stack:
      auto : false
    region:
      static: eu-west-1